#!/usr/bin/bash 

sudo cp scripts/start /usr/local/bin/.

# remove old stuff
sudo apt update && sudo apt upgrade -y
sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release -y

# remove old stuff
sudo apt remove docker docker-engine docker.io containerd runc

# add docker repo to source list
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
$(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# install docker
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io -y

# allow to start without sudo
sudo usermod -aG docker $USER


